language: ruby
cache:
  - bundler
  - pip
install:
  - gem install jekyll
  - pip install --user awscli
script: jekyll build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local-dir: _site
  acl: public_read
  on:
    repo: ryanrishi/website
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
env:
  global:
    - secure: 4QC8D+Nl9NJXZDeueKX7oMlfBHvlUiuphqZyJGGxpwNhY0zqByi7pbyNQwZH1FYDcIic6b3WBjPyGJjH0S2mlWJZLZcfgx6PCNHHJ7N1p1eRceGUKkLk45YdYVsECdnrZujc4nWzPEJYLpaYqA76nztuG05cXrX8tPjtE5S51VlDjBi+fW7pws/vTLBwbKuGxmRFBg0BAYpT0z7BdKZ0juUEspxpiPNxI1//N8qFSaT+TosMXcDwMBcPI3R+oIUic2VM0bZBoU2wjvoy0V/ONbHV2IuyyTt8jSbLNKyPlgI2k+gYH25MB+QyHRBimAE2QDswiQpdk/C+dDoqQdmZynLtTIVz5qlkehcienUSom4jnYZcciR/+Ovf75LgP0gWSpDj75h6faJuamEQS2pLFs7WuD2PcU9YHlhhhavKSp0u/DIwkJGz/tm5HZZ8ILR+bm67aBTWsiDlXOunPCRxcSD0J5UXAWfH1BkbPdEcfR3k0Bohq2/hLssEqrUrwfhTf2wATM5yZFKCAugF2ag0vtyzg15K1ObhQbAY/ujfmXSNLQJCMYqGD0NkSjYVldHXkrPsUFBtOHP+xA3SPtaarekJFwQKS8+h/5zrvvdZ0fEmQaVZ9bNoTAQWu6fpiDhppF2bdwW6vw1tKi2TUpRG6+fKNEqN8hyBC9pkxyyH2QU=
    - secure: 63MoA6u0EzZBxSRlb7oDOv2DVLtHl+WCHDFtLvO2o+3/FSQbkEEVkNplfCaLUKQkaRt7wDDWF6blWNIXMofJ8wyzx1wb/BhIDfBu6eLS4dxGBOjjN02iNts8vAXmwuIEPGpftOZrOeJSW4Z4i0KDyRRymnh2IUn6+D18pYFdn5NoRKwfh0lvh2aBgIx1khdRcOH5WIwe03Li9NWSTNEvhrgLaj1btRkt7bRrmRJJd/xmwrGZo08yu70Wpzds44lyLkCpHwEFk9QqhumbPajA5rZcHzLLJNULjSYqTLxGxoc8Wz8i018UnSX7zgzU3nVB+2qtxFcw2JeIGfplY2hbrF0omZwl8f6P+xwJX+juCL+whgC7IYHsUzvizr7wZ/6GsXCCTmhEMLKTWHgAxn7MLa21H0LPrU8F9lMSF3Sr0vRfGSagZzLpuVYEotQcF0ChZuV7vmKhp08mLHdYalMrXHaNYxx7r5uHDG8VYez2jkVqitPz5UVci8+/ILiterCH0N8NEAFeT5TCs8Z8zyy8GJtzfRlIq2MquZQfYEFoz3cWsFyk6egi+i37qsa+nDbnnvwpKrkYXsCoo4K7LbHCWVh+lmlGAaaOawVPEoW64KyWlLTzpPKlNBgXNBDMk65tmLC+ELNq2IRCqC1G0tdYPvLNELUUBGjsRjwjL3ZVHDo=
    - secure: Z7Vrds92qnre7nNvzmqedwPqcvTxNqNzaDX1bIg3GI3sIeJN5uqDTuybG1xAqhFUr/Xl9bcCRcOq7pthihSWpCBFNcqTVjYOFwbreTX29HI7ILzFRQAtsh5BG0hxMUgIH72nwcDcxNe0WXThH9Rewfwdqy/Nzyv1Rw6Uxpi/uIuaaXHGOXQvnBJ0usVU1XkxowOS1vP9ESZkQY8g6nzihnr+Rhl7sCs84iOVjIQFP0kUyue8jtgXf1P3Q7vFhKONE6MfbSNswbJaKn9OjUasbVrAO+58vrm+fagXdMdGafsL9WL5gHdVLmB6RAApv3M4cBxKicBrlmjL/aT3TZGdH38Ske4tIF95i1yQxxDN/aP+q5belikJ7u/EFKjTSqKgYauwG/AT54TFiAVxzUFw/6sHr+asM5pe9C0ew8ibAKRvoe20tWQj9kShrBp+bBM6ucXVl0SkVx0ITYoKlRwUfP8Zhr8VXATqGzpsVLnu4HxlZaj3pk94j8dCiZxuu2QcU0JzX1KhF+5b1e/D6InYg602u1ig96BbDQ0xW7+QRehNYK/7kaoPbW/mlVKBgpMrmbtFJeCUHp7ncAcSO/uIOguaNUrysLe+bD1rRTTGw4yMp+OlfEjtcfU357qgg20ta0zLxT0GyNEE9xUQbv+wA0AyzomZ34njg4u3fsjoqvs=
    - secure: BIZ5SPOoaAtxM3IOc+8RpGxW+bu+7XlbEvFvV3NaK+AxU8oVxI1JI5HNZY/CWjIUmCKL2ZjW8caEsUobFLmN3qrhVDXj0ldB7gfBaWPObfHDA/+WQNOF5WgpHkC9rsh9gAHpcG807IetgmyBNyIqKn0Ull0gZTwwBU1naaHS9abk9Fqlb91URdt73xQbaccUVhshdhrTRaLQOthFxHL5l7nTa7Tl/2Q04ujxScsEjLGuaHMi6y8x/lrRI+ZyFN7Lw+PDG7ZAvMr8z2/avA2UYZaVR759N1IR66IKs/O7ImECW5666QgRpdlwB9KJhISKAgBJh9teM4PEba6YoPQ6OrkdebiM3ompc+6xpYutYYu05L43il9RxPTSaMexPelsCw5WW/iLt840yaN6Eb/I8jAPZrRpf4pIBkAuycUNoxwSYKxwfNAqB2q2/qDG3x/cARh3z5QjjV/MiCSa9RIX4eQVZm9AKylXMKjqMhvFjZSZ2WRTT2k94zPPiQBsVPLO5YWVEbRmNHHDjHj+QZYoz3Jze2egrurlqj+e3foAmQjptango5Q7fY/GkIb3gCe3XrXQFuCiOyfqrZMLvIeHDoEMjE48KMNJMj4K9C/hztLPTQeamSgj/HawIYGUtFS4yhZzU1xZEPPb2FzIkjGqs54C+DSyAzcLExEG3EkIXlI=
