# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Rishi
email: ryan@ryanrishi.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Rishi - drum guy, brogrammer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryanrishi.com" # the base hostname & protocol for your site
twitter_username: ryanrishi
github_username:  ryanrishi
linkedin_username: ryanrishi
soundcloud_username: ryanrishi

# Build settings
markdown: kramdown
