# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Rishi
description: Full-stack software engineer and musician who loves cooking, camping, and flying.
email: ryan@ryanrishi.com
baseurl: ""
url: "https://ryanrishi.com"
twitter_username: ryanrishi
github_username:  ryanrishi
linkedin_username: ryanrishi
soundcloud_username: ryanrishi

# Build settings
markdown: kramdown
