# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Rishi
description: Full-stack software engineer and musician who loves cooking, camping, and flying.
email: ryan@ryanrishi.com
baseurl: ""
url: "https://ryanrishi.com"
twitter_username: ryanrishi
github_username:  ryanrishi
linkedin_username: ryanrishi
soundcloud_username: ryanrishi
site_image: /assets/img/ryan-lattice.jpg

# Build settings
markdown: kramdown
source: src
destination: public
exclude: ['node_modules']

collections:
  projects:
    output: true

assets:
  sources:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/videos
    - assets/javascript
    - assets/video
    - assets/image
    - assets/img
    - assets/js
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img
    - _assets/js
    - css
    - fonts
    - images
    - videos
    - javascript
    - video
    - image
    - img
    - js
