name: Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: yarn install
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          start: ./node_modules/.bin/start-server-and-test start 3000
