name: Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: yarn install
        uses: yarn install
      - name: Cypress
        uses: cypress-io/github-action@v2
