name: ESLint
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: yarn install
        uses: yarn install
      - name: ESLint
        uses: yarn eslint
