name: Percy
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: yarn install
        uses: yarn install
      - name: Percy
        uses: percy exec -- yarn test:ci
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
